"""
Cookie file writer — converts Playwright JSON cookies to Netscape HTTP Cookie
File format compatible with yt-dlp's ``cookiefile`` option.

Writes atomically via temporary file + os.replace() to prevent partial reads.
"""

import logging
import os

logger = logging.getLogger("cookie-bot.cookie_writer")

# Netscape cookie file header (required by yt-dlp)
HEADER = "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by cookie-bot. Do not edit manually.\n"


def _cookie_to_netscape(cookie: dict) -> str:
    """Convert a single Playwright cookie dict to a Netscape-format line.

    Playwright cookie format (from context.cookies()):
        {
            "name": str,
            "value": str,
            "domain": str,
            "path": str,
            "expires": float,   # Unix timestamp in seconds, -1 = session
            "httpOnly": bool,
            "secure": bool,
            "sameSite": str,
        }

    Netscape format (tab-separated):
        domain  domain_specified  path  secure  expires  name  value

    - domain_specified: TRUE if domain starts with ".", FALSE otherwise
    - HttpOnly cookies get "#HttpOnly_" prepended to the domain
    """
    domain = cookie.get("domain", "")
    # Determine if domain is a wildcard (starts with ".")
    domain_specified = "TRUE" if domain.startswith(".") else "FALSE"
    path = cookie.get("path", "/")
    secure = "TRUE" if cookie.get("secure") else "FALSE"

    # Expiry: -1 means session cookie (no expiry). Use 0 for session cookies,
    # use the actual timestamp otherwise.
    expires_raw = cookie.get("expires", -1)
    if expires_raw is None or expires_raw <= 0:
        expires = "0"
    else:
        expires = str(int(expires_raw))

    name = cookie.get("name", "")
    value = cookie.get("value", "")

    # Handle HttpOnly prefix
    if cookie.get("httpOnly"):
        domain = f"#HttpOnly_{domain}"

    return f"{domain}\t{domain_specified}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"


def write_cookie_file(playwright_cookies: list[dict], output_path: str) -> None:
    """Convert a list of Playwright cookie dicts to Netscape format and write
    atomically to ``output_path``.

    Args:
        playwright_cookies: List of cookie dicts from Playwright's
            ``context.cookies()``.
        output_path: Destination file path for the Netscape-format cookies.
    """
    lines = [HEADER]
    for cookie in playwright_cookies:
        try:
            lines.append(_cookie_to_netscape(cookie))
        except Exception as exc:
            logger.warning("Skipping malformed cookie %s: %s", cookie.get("name", "<unknown>"), exc)

    content = "".join(lines)

    # Atomic write: write to .tmp, then rename
    tmp_path = output_path + ".tmp"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(tmp_path, "w") as f:
        f.write(content)
    os.replace(tmp_path, output_path)

    logger.debug("Wrote %d cookies to %s", len(playwright_cookies), output_path)
